services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Map port 80 in the container to port 8080 on the host
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map port 3000 in the container to port 3000 on the host
    environment:
      - PORT=3000
