services:
  client:
    build:
      context: ../client
      dockerfile: ./docker/Dockerfile
      args:
        GIT_COMMIT_HASH: docker-git-commit
    ports:
      - "7373:80" # Map port 80 in the container to port 8080 on the host
    depends_on:
      - server

  server:
    build:
      context: ../server
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000" # Map port 3000 in the container to port 3000 on the host
    environment:
      - PORT=3000
    volumes:
      - ../database.db:/usr/app/database.db:delegated

  sqlite-viewer:
    image: coleifer/sqlite-web
    container_name: sqlite-viewer
    environment:
      - SQLITE_DATABASE=/data/database.db
    volumes:
      - ../database.db:/data/database.db
    ports:
      - "8081:8080"
    depends_on:
      - server
