services:
  client:
    build:
      context: ../client
      dockerfile: ./docker/Dockerfile
      args:
        GIT_COMMIT_HASH: docker-git-commit
    ports:
      - "1001:80"
    depends_on:
      - server

  server:
    build:
      context: ../server
      dockerfile: ./docker/Dockerfile
    ports:
      - "1002:3000"
    environment:
      - PORT=3000
    volumes:
      - ../database.db:/usr/app/database.db:delegated

  sqlite-viewer:
    image: coleifer/sqlite-web
    container_name: sqlite-viewer
    environment:
      - SQLITE_DATABASE=/data/database.db
    volumes:
      - ../database.db:/data/database.db
    ports:
      - "1003:8080"
    depends_on:
      - server
